# Generated by Django 5.0.7 on 2024-07-25 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_access', '0002_advertisements_cartreservation_inventory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='inventory_id',
        ),
        migrations.AddField(
            model_name='products',
            name='inventory',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
