# Generated by Django 5.0.7 on 2024-07-25 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_access', '0003_remove_products_inventory_id_products_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmedia',
            name='file_path',
        ),
        migrations.AddField(
            model_name='productmedia',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='product_media/'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='stock',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
