# Generated by Django 5.0.7 on 2024-07-25 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_access', '0004_remove_productmedia_file_path_productmedia_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='user_media/'),
        ),
    ]
