# Generated by Django 5.0.7 on 2024-07-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_access', '0005_alter_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmedia',
            name='alt_text',
            field=models.TextField(blank=True, default='Image', null=True),
        ),
    ]
