# Generated by Django 5.0.7 on 2024-07-26 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_access', '0006_alter_productmedia_alt_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='inventory_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
