# Generated by Django 5.0.7 on 2024-07-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_access', '0007_alter_productvariant_inventory_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
