# Generated by Django 5.0.7 on 2024-07-29 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_access', '0008_inventory_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='reorder_level',
            field=models.IntegerField(default=1000),
        ),
    ]
