# Generated by Django 5.0.7 on 2024-07-31 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_access', '0009_alter_inventory_reorder_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
