# Generated by Django 5.0.7 on 2024-08-02 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_access', '0012_alter_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientreport',
            name='created_by',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
