# Generated by Django 5.0.7 on 2024-08-06 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_access', '0013_clientreport_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryhistory',
            name='new_stock',
            field=models.IntegerField(default=0),
        ),
    ]
