# Generated by Django 5.0.7 on 2024-08-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_access', '0014_inventoryhistory_new_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisements',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='advertisements/'),
        ),
    ]
