# Generated by Django 5.0.7 on 2024-08-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_access', '0016_verificationotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisements',
            name='type',
            field=models.CharField(choices=[('MAINPANEL', 'Main Panel'), ('SUBPANEL', 'Sub Panel')], default='SUBPANEL', max_length=20),
        ),
    ]
