# Generated by Django 5.0.7 on 2024-08-08 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_access', '0017_advertisements_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
