# Generated by Django 5.0.7 on 2024-08-08 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_access', '0018_products_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationotp',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='verificationotp',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
