# Generated by Django 5.0.7 on 2024-08-16 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_access', '0023_alter_categories_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartreservation',
            name='status',
            field=models.CharField(choices=[('RESERVED', 'Reserved'), ('EXPIRED', 'Expired'), ('ORDERED', 'Ordered')], default='RESERVED', max_length=10),
        ),
    ]
