# Generated by Django 5.0.7 on 2024-08-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_access', '0025_alter_order_payment_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='change_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
