# Generated by Django 5.0.7 on 2024-08-22 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_access', '0027_clientmessages'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmessages',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
