# Generated by Django 5.0.7 on 2024-08-23 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_access', '0028_clientmessages_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmessages',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('REPLIED', 'Replied'), ('CLOSED', 'Closed')], default='OPEN', max_length=20),
        ),
        migrations.AddField(
            model_name='clientmessages',
            name='updated_by',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
