"""
Django settings for Ecommerce project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os

from pathlib import Path
from celery.schedules import crontab

from Ecommerce.dataaccess.ecommerce_access.db import DATABASES

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-a!4&d^wlnezjbjeipy#xla!%*lgx(v_9e-9)newqsg587d$u&t'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Ecommerce',
    'Ecommerce.dataaccess',
    'Ecommerce.dataaccess.ecommerce_access',
    'Ecommerce.admin_panel',
    'Ecommerce.common',
    'Ecommerce.admin_panel.products',
    'Ecommerce.admin_panel.inventory',
    'Ecommerce.admin_panel.users',
    'Ecommerce.admin_panel.orders',
    'Ecommerce.admin_panel.dashboard',
    'Ecommerce.admin_panel.advertisement',
    'Ecommerce.admin_panel.client_messages',
    'Ecommerce.client_panel',
    'Ecommerce.client_panel.homepage',
    'Ecommerce.client_panel.client_products',
    'Ecommerce.client_panel.client_signup',
    'Ecommerce.client_panel.client_profile',
    'Ecommerce.client_panel.cart',
    'Ecommerce.client_panel.client_order',
    'Ecommerce.client_panel.wishlist',
    'captcha',
    'stripe',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Ecommerce.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'common', 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Ecommerce.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES=DATABASES

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Additional locations of static files (directories where Django will look for static files)
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),  # Example: for app-level static files
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# AUTH_USER_MODEL = 'Ecommerce.dataaccess.ecommerce_access.user_models.CustomUser'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = 'josephalan657@gmail.com'
EMAIL_HOST_PASSWORD = 'egnumglargjeazlh'
EMAIL_USE_SSL=False
DEFAULT_FROM_EMAIL = 'josephalan657@gmail.com'


CELERY_BROKER_URL = 'redis://localhost:6379'
CELERY_RESULT_BACKEND = 'redis://localhost:6379'
# CELERY_BEAT_SCHEDULE = {
#     'check-inventory': {
#         'task': 'Ecommerce.tasks.check_inventory',
#         'schedule': 3600.0,  # every hour
#     },
# }


SESSION_COOKIE_AGE = 3600


STRIPE_SECRET_KEY = ''
STRIPE_PUBLISHABLE_KEY = ''